### ISSUE TITLE
Task: Linkedln-Post

### ISSUE THREAD

**Issue by teerth17** [ykdojo/OpenStream#15]
## Project Task

- [ ] **Create and Share a LinkedIn Post Version of [This Thread](https://twitter.com/ykdojo/status/1747809356702433430)**
  - Summarize the project, its goals, and the progress in a LinkedIn post.

**Comment by Pddubey** [comment]
**How to Build Experience To land a good Job In Tech.**

One of the most impactful way to build your skills even before landing that dream job is

**Open Source Contribution:**
Dive into the world of open source. Contribute to projects, collaborate with experienced developers, and showcase your skills. It's not just about coding; it's about learning how to work in collaborative development and building great softwares together. 

Therefore We 

**Announcing a New Open Source Project for All of You:** 

**Chrome Extension for WebCam And Screen Recording - OpenStream🎥**

A Simple Chrome Extension That enable users to record their screen and webcam at the same time. What sets this project apart ?

 The recordings are saved in separate files. It enables users to edit recordings in any desired manner. Making it particularly handy for tasks like creating coding tutorials.

Though in market similar software like Screenflow and Camtasia could be found but the problem is they are very costly like $100 USD🤯.  

But we believe to make OpenStream publically free of cost to everyone🥳 

If you're passionate about open source and interested in contributing to this project, We'd love to hear from you! Let's collaborate, learn, and build something impactful together.

Drop a comment or DM if you're ready to  join us in this amazing journey. Together, we can make OpenStream successful and gain a great Learning experience.

#TechJourney #OpenSource #ChromeExtension #TechOpportunities

**Comment by Pddubey** [comment]
@ykdojo Need any modification ?

**Comment by ykdojo** [comment]
@Pddubey I find that what you wrote has a lot of inconsistent/random casing issues. Could you fix them?

**Comment by ykdojo** [comment]
I cleaned up the original post and scheduled it to go out from my personal account.

![Image](https://github.com/ykdojo/OpenStream/assets/1811651/6756c0e8-a770-4054-a61b-82e6af4c0c73)

![Image](https://github.com/ykdojo/OpenStream/assets/1811651/3697fead-1e40-474d-b8ef-609ed264484c)
